from typing import Final

CLASS_TO_TEXT: Final[dict[str, str]] = {
    "2": 'Success',
    "4": 'Persistent Transient Failure',
    "5": 'Permanent Failure'
}

SUBJECT_TO_TEXT: Final[dict[str, str]] = {
    # "0": 'Other or Undefined Status',
    "1": 'Addressing Status',
    "2": 'Mailbox Status',
    "3": 'Mail System Status',
    "4": 'Network and Routing Status',
    "5": 'Mail Delivery Protocol Status',
    "6": 'Message Content or Media Status',
    "7": 'Security or Policy Status'
}

SUBJECT_DETAIL_TO_TEXT: Final[dict[tuple[str, str], str]] = {
    # ("0", "0"): "Other undefined Status",
    # ("1", "0"): "Other address status",
    ("1", "1"): "Bad destination mailbox address",
    ("1", "2"): "Bad destination system address",
    ("1", "3"): "Bad destination mailbox address syntax",
    ("1", "4"): "Destination mailbox address ambiguous",
    ("1", "5"): "Destination address valid",
    ("1", "6"): "Destination mailbox has moved, No forwarding address",
    ("1", "7"): "Bad sender's mailbox address syntax",
    ("1", "8"): "Bad sender's system address",
    ("1", "9"): "Message relayed to non-compliant mailer",
    ("1", "10"): "Recipient address has null MX",
    ("2", "0"): "Other or undefined mailbox status",
    ("2", "1"): "Mailbox disabled, not accepting messages",
    ("2", "2"): "Mailbox full",
    ("2", "3"): "Message length exceeds administrative limit",
    ("2", "4"): "Mailing list expansion problem",
    ("3", "0"): "Other or undefined mail system status",
    ("3", "1"): "Mail system full",
    ("3", "2"): "System not accepting network messages",
    ("3", "3"): "System not capable of selected features",
    ("3", "4"): "Message too big for system",
    ("3", "5"): "System incorrectly configured",
    ("3", "6"): "Requested priority was changed",
    ("4", "0"): "Other or undefined network or routing status",
    ("4", "1"): "No answer from host",
    ("4", "2"): "Bad connection",
    ("4", "3"): "Directory server failure",
    ("4", "4"): "Unable to route",
    ("4", "5"): "Mail system congestion",
    ("4", "6"): "Routing loop detected",
    ("4", "7"): "Delivery time expired",
    ("5", "0"): "Other or undefined protocol status",
    ("5", "1"): "Invalid command",
    ("5", "2"): "Syntax error",
    ("5", "3"): "Too many recipients",
    ("5", "4"): "Invalid command arguments",
    ("5", "5"): "Wrong protocol version",
    ("5", "6"): "Authentication Exchange line is too long",
    ("6", "0"): "Other or undefined media error",
    ("6", "1"): "Media not supported",
    ("6", "2"): "Conversion required and prohibited",
    ("6", "3"): "Conversion required but not supported",
    ("6", "4"): "Conversion with loss performed",
    ("6", "5"): "Conversion Failed",
    ("6", "6"): "Message content not available",
    ("6", "7"): "Non-ASCII addresses not permitted for that sender/recipient",
    ("6", "8"): "UTF-8 string reply is required, but not permitted by the SMTP client",
    ("6", "9"): "UTF-8 header message cannot be transferred to one or more recipients, so the message must be rejected",
    # ("6", "10"): None,
    ("7", "0"): "Other or undefined security status",
    ("7", "1"): "Delivery not authorized, message refused",
    ("7", "2"): "Mailing list expansion prohibited",
    ("7", "3"): "Security conversion required but not possible",
    ("7", "4"): "Security features not supported",
    ("7", "5"): "Cryptographic failure",
    ("7", "6"): "Cryptographic algorithm not supported",
    ("7", "7"): "Message integrity failure",
    ("7", "8"): "Authentication credentials invalid",
    ("7", "9"): "Authentication mechanism is too weak",
    ("7", "10"): "Encryption Needed",
    ("7", "11"): "Encryption required for requested authentication mechanism",
    ("7", "12"): "A password transition is needed",
    ("7", "13"): "User Account Disabled",
    ("7", "14"): "Trust relationship required",
    ("7", "15"): "Priority Level is too low",
    ("7", "16"): "Message is too big for the specified priority",
    ("7", "17"): "Mailbox owner has changed",
    ("7", "18"): "Domain owner has changed",
    ("7", "19"): "RRVS test cannot be completed",
    ("7", "20"): "No passing DKIM signature found",
    ("7", "21"): "No acceptable DKIM signature found",
    ("7", "22"): "No valid author-matched DKIM signature found",
    ("7", "23"): "SPF validation failed",
    ("7", "24"): "SPF validation error",
    ("7", "25"): "Reverse DNS validation failed",
    ("7", "26"): "Multiple authentication checks failed",
    ("7", "27"): "Sender address has null MX",
    ("7", "28"): "Mail flood detected",
    ("7", "29"): "ARC validation failure",
    ("7", "30"): "REQUIRETLS support required"
}
